version: '3'

services:
    postgres:
        image: postgres:16-alpine
        container_name: mahsa_postgres
        ports:
            - ${POSTGRES_HOST_PORT:-13742}:5432
        volumes:
            - ./AppData/postgres:/var/lib/postgresql/data
            - ./Data:/code
            - ./AppData/backup:/backup
            - ./AppData/archive:/archive
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-mahsa}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mahsa}
            - POSTGRES_DB=${POSTGRES_DB:-postgres}
            - POSTGRES_SCHEMA=${POSTGRES_SCHEMA:-mahsa}
        profiles:
            - db
            - app

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: mahsa_zookeeper
        ports:
            - ${ZOOKEEPER_HOST_PORT:-2181}:2181
        restart: unless-stopped
        profiles:
            - app

    kafka:
        image: wurstmeister/kafka
        container_name: mahsa_kafka
        ports:
            - ${KAFKA_HOST_PORT:-9092}:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: '${KAFKA_TOPICS}:-T1_TS:1:1,T2_LA:1:1,T3_DB:1:1'
        restart: unless-stopped
        depends_on:
            - zookeeper
        profiles:
            - app

    nocodb:
        depends_on:
            root_db:
                condition: service_healthy
        environment:
            NC_DB: 'pg://root_db:5432?u=postgres&p=password&d=root_db'
            NC_JWT_EXPIRES_IN: ${NC_JWT_EXPIRES_IN:-48h}
            NC_ADMIN_EMAIL: ${NC_ADMIN_EMAIL:-machil@gmail.com}
            NC_ADMIN_PASSWORD: ${NC_ADMIN_PASSWORD:-12345678}
        image: 'nocodb/nocodb:0.204.4'
        ports:
            - '${NOCODB_HOST_PORT:-8080}:8080'
        restart: always
        volumes:
            - './AppData/Nocodb:/usr/app/data'
        profiles:
            - app
            - nocodb

    root_db:
        environment:
            POSTGRES_DB: root_db
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
        healthcheck:
            interval: 10s
            retries: 10
            test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
            timeout: 2s
        image: postgres:16-alpine
        ports:
            - '16585:5432'
        restart: always
        volumes:
            - './AppData/nocodb-pg:/var/lib/postgresql/data'
        profiles:
            - app
            - nocodb
